SELECT * FROM V1;

CREATE VIEW V1 AS (SELECT PrName FROM Products);

ALTER VIEW V1 AS (SELECT PrName AS NAME, PrPrice AS PRICE FROM Products WHERE PrPrice > 700)

INSERT INTO V1 VALUES ('Product17', '1432')

ALTER VIEW V1 AS (SELECT PrName AS NAME, PrPrice AS PRICE FROM Products WHERE PrPrice > 700) WITH CHECK OPTION

INSERT INTO V1 VALUES ('Product18', '200')

DROP VIEW V1;

SELECT * FROM V2;

DROP VIEW V2;